theme: jekyll-theme-cayman
title: Holography, bit threads, and islands
image: "pics/andrew.jpg"
description: Read about my research
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
