theme: jekyll-theme-cayman
title: Holography, bit threads, and islands
description: Read about my research
remote_theme: pages-themes/architect
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
